---
- name: Install Java 17
  hosts: all
  become: yes

  vars:
    java_package: openjdk-17-jdk

  tasks:
    - name: Install Java 17
      apt:
        name: "{{ java_package }}"
        state: present
        update_cache: yes

    - name: Verify Java version
      command: java -version
      register: java_output
      ignore_errors: true

    - name: Print Java version
      debug:
        msg: "{{ java_output.stderr_lines }}"
